routes/web.php
<?php

use App\Http\Controllers\Test\TestController;
use App\Http\Controllers\Konter\KonterController;
use App\Http\Controllers\LandingPage\LandingPageController;
use App\Http\Controllers\Logout\LogoutController;
use App\Http\Controllers\Region\DistrictController;
use App\Http\Controllers\Region\ProvinceController;
use App\Http\Controllers\Region\RegencyController;
use App\Http\Controllers\Region\VillageController;
use App\Http\Livewire\Back\Dashboard\DashboardPage;
use App\Http\Livewire\Back\Image\CreateImagePage;
use App\Http\Livewire\Back\Image\EditImagePage;
use App\Http\Livewire\Back\Image\ImagePage;
use App\Http\Livewire\Back\Login\LoginPage;
use App\Http\Livewire\Back\Pos\CreatePosPage;
use App\Http\Livewire\Back\Pos\EditPosPage;
use App\Http\Livewire\Back\Pos\PosPage;
use App\Http\Livewire\Back\Region\CreateRegionPage;
use App\Http\Livewire\Back\Region\EditRegionPage;
use App\Http\Livewire\Back\Region\Partials\CityPage;
use App\Http\Livewire\Back\Region\Partials\DistrictPage;
use App\Http\Livewire\Back\Region\Partials\ProvincePage;
use App\Http\Livewire\Back\Region\Partials\VillagePage;
use App\Http\Livewire\Back\Region\RegionPage;
use App\Http\Livewire\Back\Setting\CreateSettingPage;
use App\Http\Livewire\Back\Setting\EditSettingPage;
use App\Http\Livewire\Back\Setting\SettingPage;

use App\Http\Livewire\Back\User\UserPage;
use App\Http\Livewire\Back\User\CreateUserPage;
use App\Http\Livewire\Back\User\EditUserPage;

use App\Http\Livewire\Back\Role\RolePage;
use App\Http\Livewire\Back\Role\CreateRolePage;
use App\Http\Livewire\Back\Role\EditRolePage;

use App\Http\Livewire\Front\CoomingSoon\CoomingSoonPage;
use App\Http\Livewire\Front\Landing\LandingPage;
use Illuminate\Support\Facades\Route;


// Route::get('/', LandingPage::class)->name('landing-page');
Route::get('/', CoomingSoonPage::class)->name('comingsoon');
Route::get('/maps', LandingPageController::class)->name('landing-page');
Route::post('/getRegencys', [LandingPageController::class, 'getRegencies']);
Route::post('/getDistricts', [LandingPageController::class, 'getDistricts']);
Route::post('/getVillages', [LandingPageController::class, 'getVillages']);
Route::post('/getPosCodeVill', [LandingPageController::class, 'getPosCodeVill']);
Route::post('/getProvGeoJSON', [LandingPageController::class, 'getProvGeoJSON']);
Route::post('/getRegGeoJSON', [LandingPageController::class, 'getRegGeoJSON']);
Route::post('/getDisGeoJSON', [LandingPageController::class, 'getDisGeoJSON']);
Route::post('/getVilGeoJSON', [LandingPageController::class, 'getVilGeoJSON']);
Route::post('/getGeoJSON', [LandingPageController::class, 'getGeoJSON']);
Route::post('/getKonterGeoJSON', [LandingPageController::class, 'getKonterGeoJSON']);
Route::post('/getUrlDownload', [LandingPageController::class, 'getUrlDownload']);
Route::post('/download', [LandingPageController::class, 'downloadImg']);
Route::post('/downloadVill', [LandingPageController::class, 'downloadImgVill']);
Route::get('/download-image/{image}', [LandingPageController::class, 'downloadImages']);


//Logout
Route::get('logout', [LogoutController::class, 'logout'])->name('logout');

Route::get('/back-office/auth', LoginPage::class)->name('login');

Route::group(['middleware' => 'auth'], function () {
    Route::group(['prefix' => 'back-office', 'as' => 'back-office.'], function () {

        // Dashboard
        Route::get('/', DashboardPage::class)->name('dashboard');

        // User
        Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
            Route::get('/', UserPage::class)->name('index')->middleware('permission:View User');
            Route::get('/create', CreateUserPage::class)->name('create')->middleware('permission:Add User');
            Route::get('/edit/{id}', EditUserPage::class)->name('edit')->middleware('permission:Edit User');
        });

        // Role
        Route::group(['prefix' => 'role', 'as' => 'role.'], function () {
            Route::get('/', RolePage::class)->name('index')->middleware('permission:View Role');
            Route::get('/create', CreateRolePage::class)->name('create')->middleware('permission:Add Role');
            Route::get('/edit/{id}', EditRolePage::class)->name('edit')->middleware('permission:Edit Role');
        });

        // Region
        Route::group(['prefix' => 'region', 'as' => 'region.'], function () {
            Route::get('/province', ProvincePage::class)->name('province')->middleware('permission:View Provinsi');
            Route::get('/create-province', [ProvinceController::class, 'create'])->name('create-province')->middleware('permission:Add Provinsi');
            Route::post('/store-province', [ProvinceController::class, 'store'])->name('store-province')->middleware('permission:Add Provinsi');
            Route::get('/edit-province/{id}', [ProvinceController::class, 'edit'])->name('edit-province')->middleware('permission:Edit Provinsi');
            Route::post('/update-province/{id}', [ProvinceController::class, 'update'])->name('update-province')->middleware('permission:Edit Provinsi');

            Route::get('/city', CityPage::class)->name('city')->middleware('permission:View Kota/Kabupaten');
            Route::get('/create-regency', [RegencyController::class, 'create'])->name('create-regency')->middleware('permission:Add Kota/Kabupaten');
            Route::post('/store-regency', [RegencyController::class, 'store'])->name('store-regency')->middleware('permission:Add Kota/Kabupaten');
            Route::get('/edit-regency/{id}', [RegencyController::class, 'edit'])->name('edit-regency')->middleware('permission:Edit Kota/Kabupaten');
            Route::post('/update-regency/{id}', [RegencyController::class, 'update'])->name('update-regency')->middleware('permission:Edit Kota/Kabupaten');

            Route::get('/district', DistrictPage::class)->name('district')->middleware('permission:View Kecamatan');
            Route::get('/create-district', [DistrictController::class, 'create'])->name('create-district')->middleware('permission:Add Kecamatan');
            Route::post('/store-district', [DistrictController::class, 'store'])->name('store-district')->middleware('permission:Add Kecamatan');
            Route::get('/edit-district/{id}', [DistrictController::class, 'edit'])->name('edit-district')->middleware('permission:Edit Kecamatan');
            Route::post('/update-district/{id}', [DistrictController::class, 'update'])->name('update-district')->middleware('permission:Edit Kecamatan');

            Route::get('/village', VillagePage::class)->name('village')->middleware('permission:View Kelurahan');
            Route::get('/create-village', [VillageController::class, 'create'])->name('create-village')->middleware('permission:Add Kelurahan');
            Route::post('/store-village', [VillageController::class, 'store'])->name('store-village')->middleware('permission:Add Kelurahan');
            Route::get('/edit-village/{id}', [VillageController::class, 'edit'])->name('edit-village')->middleware('permission:Edit Kelurahan');
            Route::post('/update-village/{id}', [VillageController::class, 'update'])->name('update-village')->middleware('permission:Edit Kelurahan');
        });

        // Pos
        Route::group(['prefix' => 'pos', 'as' => 'pos.'], function () {
            Route::get('/', PosPage::class)->name('index')->middleware('permission:View Konter');
            Route::get('/create', [KonterController::class, 'create'])->name('create')->middleware('permission:Add Konter');
            Route::post('/store', [KonterController::class, 'store'])->name('store')->middleware('permission:Add Konter');
            Route::get('/edit/{id}', [KonterController::class, 'edit'])->name('edit')->middleware('permission:Edit Konter');
            Route::post('/update/{id}', [KonterController::class, 'update'])->name('update')->middleware('permission:Edit Konter');
            Route::get('/download/{id}', [KonterController::class, 'download'])->name('download')->middleware('permission:View Konter');
        });

        Route::group(['prefix' => 'konter', 'as' => 'konter.'], function () {
            Route::post('/getRegencys', [KonterController::class, 'getRegencies']);
            Route::post('/getDistricts', [KonterController::class, 'getDistricts']);
            Route::post('/getVillages', [KonterController::class, 'getVillages']);
            Route::get('/download/{geojson}', [KonterController::class, 'download']);
        });
    });
});

app/Models/Konter.php
<?php

namespace App\Models;

use App\Traits\HasUuid;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Konter extends Model
{
    use HasUuid;

    protected $fillable = [
        'postalcode',
        'province_code',
        'regency_code',
        'district_code',
        'village_code',
        'category',
        'image',
        'geojson',
    ];

    public function scopeFilter($query, array $filters)
    {
        $query->when($filters['search'] ?? false, function ($query, $search) {
            return $query->where('province_code', 'like', '%' . $search . '%')
                ->orWhere('postalcode', 'like', '%' . $search . '%');
        });
    }

    public function provinces()
    {
        return $this->belongsTo(Province::class, 'province_code', 'code');
    }

    public function regency()
    {
        return $this->belongsTo(Regency::class, 'regency_code', 'code');
    }

    public function district()
    {
        return $this->belongsTo(District::class, 'district_code', 'code');
    }

    public function village()
    {
        return $this->belongsTo(Village::class, 'village_code', 'code');
    }
}

app/Http/Controllers/Konter/KonterController.php
<?php

namespace App\Http\Controllers\Konter;

use App\Models\Konter;
use App\Models\Regency;
use App\Models\Village;
use App\Models\District;
use App\Models\Province;
use App\Http\Controllers\Controller;
use Response;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class KonterController extends Controller
{
    public function index()
    {
        $konters = DB::table('konters')->orderBy('id', 'desc')->paginate(5);
        return view('admin.pages.konter.index', compact('konters'));
    }

    public function getRegencies(Request $request)
    {
        $data['regencies'] = Regency::where("province_code", $request->province_code)
            ->get(["name", "code"]);
        return response()->json($data);
    }
    public function getDistricts(Request $request)
    {
        $data['districts'] = District::where("regency_code", $request->regency_code)
            ->get(["name", "code"]);
        return response()->json($data);
    }
    public function getVillages(Request $request)
    {
        $data['villages'] = Village::where("district_code", $request->district_code)
            ->get(["name", "code"]);
        return response()->json($data);
    }

    public function create()
    {
        $data['provinces'] = Province::get(["name", "code"]);

        return view('admin.pages.pos.create', $data);
    }

    public function store(Request $request)
    {
        $request->validate([

            'postalcode' => 'required|numeric',
            'province_code' => 'required|string',
            'regency_code' => 'required|string',
            'district_code' => 'required|string',
            'village_code' => 'required|string',
            'image' => 'nullable',
            'geojson' => 'nullable',
            'category' => 'nullable',

        ]);

        $imgName = null;
        $geojsonName = null;

        if ($request->image) {
            $imgName = time() . '-image.' . $request->image->getClientOriginalExtension();
            $request->image->move(public_path('konterImg'), $imgName);
        }

        if ($request->geojson) {
            $gJson =  time() . '-' . $request->postalcode . '-geojson.' . $request->geojson->getClientOriginalExtension();
            $request->geojson->move(public_path('geojson'), $gJson);

            $geojsonName = 'geojson/' . $gJson;
        }

        Konter::create([
            'postalcode' => $request->postalcode,
            'province_code' => $request->province_code,
            'regency_code' => $request->regency_code,
            'district_code' => $request->district_code,
            'village_code' => $request->village_code,
            'category' => $request->category,
            'image' => $imgName,
            'geojson' => $geojsonName,
        ]);


        notice('success', 'Data Added Successfully');
        return redirect()->route('back-office.pos.index');
    }

    public function edit($id)
    {
        $data['provinces'] = Province::get(["name", "code"]);

        $konters = Konter::findOrFail($id);
        return view('admin.pages.pos.edit', $data, compact('konters'));
    }


    public function update(Request $request, $id)
    {
        $request->validate([

            'postalcode' => 'required|string',
            'province_code' => 'required|string',
            'regency_code' => 'required|string',
            'district_code' => 'required|string',
            'village_code' => 'required|string',
            'image' => 'nullable',
            'geojson' => 'nullable',
            'category' => 'nullable',

        ]);

        $konter = Konter::find($id);

        $imgName = $konter->image;
        $geojsonName = $konter->geojson;

        if ($request->image) {
            $imgName = time() . '-image.' . $request->image->getClientOriginalExtension();
            $request->image->move(public_path('konterImg'), $imgName);
        }

        if ($request->geojson) {
            $gJson =  time() . '-' . $konter->postalcode . '-geojson.' . $request->geojson->getClientOriginalExtension();
            $request->geojson->move(public_path('geojson'), $gJson);

            $geojsonName = 'geojson/' . $gJson;
        }

        $konter->update([
            'postalcode' => $request->postalcode,
            'province_code' => $request->province_code,
            'regency_code' => $request->regency_code,
            'district_code' => $request->district_code,
            'village_code' => $request->village_code,
            'category' => $request->category,
            'image' => $imgName,
            'geojson' => $geojsonName,
        ]);

        notice('success', 'Data Updated Successfully');
        return redirect()->route('back-office.pos.index');
    }

    public function download($id)
    {
        $konters = Konter::find($id);
        $filePath = public_path() . "/" . $konters->geojson;
        $headers = ['Content-Type: application/json'];
        $fileName = $konters->geojson;

        return Response::download($filePath, $fileName, $headers);
    }

    public function destroy($id)
    {
        Konter::find($id)->delete();
        return redirect()->route('back-office.pos.index');
    }
}

resources/views/admin/pages/konter/index.blade.php
@extends('admin.layout.master')
@section('content')
    <div class="content d-flex flex-column flex-column-fluid" id="kt_content">
        <!--begin::Subheader-->
        <div class="subheader py-2 py-lg-6 subheader-solid" id="kt_subheader">
            <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
                <!--begin::Info-->
                <div class="d-flex align-items-center flex-wrap mr-1">
                    <!--begin::Page Heading-->
                    <div class="d-flex align-items-baseline flex-wrap mr-5">
                        <!--begin::Page Title-->
                        <h5 class="text-dark font-weight-bold my-1 mr-5">Manage Content</h5>
                        <!--end::Page Title-->
                        <!--begin::Breadcrumb-->
                        <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">

                            <li class="breadcrumb-item">
                                <a href="" class="text-muted">Konter</a>
                            </li>
                        </ul>
                        <!--end::Breadcrumb-->
                    </div>
                    <!--end::Page Heading-->
                </div>
                <!--end::Info-->
            </div>
        </div>
        <!--end::Subheader-->
        <!--begin::Entry-->
        <div class="d-flex flex-column-fluid">
            <!--begin::Container-->
            <div class="container">
                <!--begin::Card-->
                <div class="card card-custom">
                    <div class="card-header flex-wrap border-0 pt-6 pb-0">
                        <div class="card-title">
                            <h3 class="card-label">
                                Konter
                            </h3>
                        </div>
                        <div class="card-toolbar">
                            <a href="{{ route('back-office.konter.create') }}"
                                class="btn btn-primary font-weight-bolder btn-xs">
                                <i class="fas fa-plus-circle"></i>
                                Tambah
                            </a>
                        </div>
                    </div>

                    <div class="card-body">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Image</th>
                                    <th>Kode Pos</th>
                                    <th>Unduh GeoJSON</th>
                                    <th class="text-center">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($konters as $item)
                                    <tr>
                                        <td style="vertical-align: middle">
                                            <img src="/konterImg/{{ $item->image }}" width="100px">
                                        </td>
                                        <td style=" vertical-align: middle">{{ $item->postalcode }}
                                        </td>
                                        <td style="vertical-align: middle">
                                            <a href="{{ url('/back-office/konter/download', $item->geojson) }}">
                                                <button type="button" title="Download" alt=" Download"
                                                    class="btn btn-sm btn-success">
                                                    Unduh
                                                </button>
                                            </a>
                                        </td>
                                        <td class="text-center" style="vertical-align: middle">
                                            <a href="/back-office/konter/{{ $item->id }}/edit" title="Edit" alt="Edit"
                                                class="btn btn-sm btn-warning btn-icon">
                                                <i class="far fa-edit"></i>
                                            </a>
                                            <form action="/back-office/konter/{{ $item->id }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button title="Delete" alt=" Delete" class="btn btn-sm btn-danger btn-icon">
                                                    <i class="far fa-trash-alt"></i></button>
                                            </form>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="5" class="text-center">
                                            Belum Ada Data
                                        </td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                        <hr>
                        {{ $konters->links() }}
                    </div>
                </div>
            </div>
            <!--end::Container-->
        </div>
        <!--end::Entry-->
    </div>
@endsection